### ISSUE TITLE
functorch grad for the mnist example

### ISSUE THREAD

**Issue by v0lta** [Machine-Learning-Foundations/day_11_exercise_neural_networks#6]
TODO: Use functorch grad for the first example @loki-veera .
Plase take a look at https://github.com/Machine-Learning-Foundations/day_02_exercise_optimization_solution/blob/main/src/optimize_2d_momentum_bumpy_torch.py , so people can connect to day 2.

**Comment by loki-veera** [comment]
It is implemented now. Closing this issue.
